# Generated by Django 6.0.4 on 2026-05-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_engine', '0004_twinsettings_last_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastchoice',
            name='choice_made',
            field=models.TextField(help_text="The AI's prediction/response"),
        ),
        migrations.AlterField(
            model_name='pastchoice',
            name='scenario',
            field=models.TextField(help_text='The situation given to the AI'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='favorite_genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='personality_traits',
            field=models.TextField(blank=True, help_text='e.g., Early bird, Tech enthusiast, Cricket lover', null=True),
        ),
    ]
