# Generated by Django 6.0.4 on 2026-05-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_engine', '0005_alter_pastchoice_choice_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastchoice',
            name='is_accurate',
            field=models.BooleanField(blank=True, help_text='Did the user agree with this?', null=True),
        ),
    ]
